/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelArbrePlan.java
 *
 * Created on 2 mars 2010, 18:38:14
 */

package fr.alma.asr.gui.tree;

import fr.alma.asr.gui.Controleur;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Le_Clubber
 */
public class PanelArbrePlan extends javax.swing.JPanel {

    /** Creates new form PanelArbrePlan */
    public PanelArbrePlan() {
		initialisation();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane2 = new javax.swing.JScrollPane();
        arbrePlan = new javax.swing.JTree(this.racinePlan);

        scrollPane2.setViewportView(arbrePlan);
        DefaultTreeModel treeModel2 = (DefaultTreeModel) arbrePlan.getModel();
        treeModel2.setAsksAllowsChildren(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbrePlan;
    private javax.swing.JScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables

    private DefaultMutableTreeNode racinePlan;
	private Controleur controleur;

	private void initialisation() {
		this.controleur = Controleur.getInstance();
		this.racinePlan = new DefaultMutableTreeNode("Plan");
		controleur.construireArbrePlan(this.racinePlan);
	}

}
