/*
 * DialogProprietes.java
 *
 * Created on 7 mars 2010, 15:52:55
 */

package fr.alma.asr.gui.tree;

import fr.alma.asr.gui.Controleur;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;

/**
 * Dialog d'affichage des propriétés.
 * @author Braud Jeremy
 */
public class DialogProprietes extends javax.swing.JDialog {

    /** Creates new form DialogProprietes. */
    public DialogProprietes(java.awt.Frame parent, String nom, String type, String dossier, Date creation, Date modif) {
        super(parent, true);
		setLocationRelativeTo(null);
        initComponents();
		initialisation(nom, type, dossier, creation, modif);

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			Controleur.printLog(Level.SEVERE, e.getMessage());
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelDossier = new javax.swing.JLabel();
        jLabelCreation = new javax.swing.JLabel();
        jLabelModif = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelDossier = new javax.swing.JLabel();
        labelCreation = new javax.swing.JLabel();
        labelModifs = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNom.setText("Nom :");

        jLabelType.setText("Type :");

        jLabelDossier.setText("Chemin d'accès :");

        jLabelCreation.setText("Date de création :");

        jLabelModif.setText("Date de modification :");

        labelNom.setText("nom");

        labelDossier.setText("dossier");

        labelCreation.setText("création");

        labelModifs.setText("modification");

        labelType.setText("type");

        fermer.setText(" Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fermer)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCreation)
                            .addComponent(jLabelModif)
                            .addComponent(jLabelDossier)
                            .addComponent(jLabelType)
                            .addComponent(jLabelNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNom)
                            .addComponent(labelType)
                            .addComponent(labelModifs)
                            .addComponent(labelCreation)
                            .addComponent(labelDossier))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(labelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(labelType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDossier)
                    .addComponent(jLabelDossier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreation)
                    .addComponent(jLabelCreation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModifs)
                    .addComponent(jLabelModif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
		this.setVisible(false);
	}//GEN-LAST:event_fermerActionPerformed

    /**
	 * The main function.
    * @param args the command line arguments
    */
    public static void main(String[] args) {
		new DialogProprietes(null, "fichier test", "Fichier", "/dtc/ici", new Date(), new Date()).setVisible(true);
		System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabelCreation;
    private javax.swing.JLabel jLabelDossier;
    private javax.swing.JLabel jLabelModif;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel labelCreation;
    private javax.swing.JLabel labelDossier;
    private javax.swing.JLabel labelModifs;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelType;
    // End of variables declaration//GEN-END:variables

	private void initialisation(String nom, String type, String dossier, Date creation, Date modif) {
		this.labelNom.setText(nom);
		this.labelType.setText(type);
		this.labelDossier.setText(dossier);

		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy - hh:mm");
		this.labelCreation.setText(dateFormat.format(creation));
		this.labelModifs.setText(dateFormat.format(modif));
	}

}
