/*
 * NewJPanel.java
 *
 * Created on 8 févr. 2010, 19:00:03
 */

package fr.alma.asr.ihm.onglets;

import java.awt.Color;
import javax.swing.JTabbedPane;

/**
 *
 * @author Le_Clubber
 */
public class PanelOnglets extends javax.swing.JPanel {

	private JTabbedPane onglets;

    /** Creates new form NewJPanel */
    public PanelOnglets(JTabbedPane pane, String titre) {
        initComponents();
		this.onglets = pane;
		this.labelNom.setText(titre+"  ");
		this.labelNom.setSize(10, 10);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNom = new javax.swing.JLabel();
        bouton = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(null);
        setLayout(new java.awt.BorderLayout());

        labelNom.setText("Nom");
        add(labelNom, java.awt.BorderLayout.LINE_START);

        bouton.setText("x");
        bouton.setToolTipText("Fermer");
        bouton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bouton.setBorderPainted(false);
        bouton.setContentAreaFilled(false);
        bouton.setFocusable(false);
        bouton.setPreferredSize(new java.awt.Dimension(15, 15));
        bouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boutonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boutonMouseExited(evt);
            }
        });
        bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonActionPerformed(evt);
            }
        });
        add(bouton, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

	private void boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonActionPerformed
		System.out.println("fermer l'onglet");
		int i = onglets.indexOfTabComponent(this);
		if (i != -1) {
			onglets.remove(i);
		}
	}//GEN-LAST:event_boutonActionPerformed

	private void boutonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonMouseEntered
		bouton.setBorderPainted(true);
		bouton.setForeground(Color.red);
	}//GEN-LAST:event_boutonMouseEntered

	private void boutonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonMouseExited
		bouton.setBorderPainted(false);
		bouton.setForeground(Color.black);
	}//GEN-LAST:event_boutonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton;
    private javax.swing.JLabel labelNom;
    // End of variables declaration//GEN-END:variables

}
