/*
 * FenetrePrincipale.java
 *
 * Created on 9 févr. 2010, 18:46:47
 */

package fr.alma.asr.ihm;

import javax.swing.JOptionPane;

/**
 * Classe gérant la fenetre principale.
 * @author Braud Jeremy
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /** Creates new form FenetrePrincipale. */
    public FenetrePrincipale() {
		Controleur.debutChargement();
        initComponents();
		initialisation();
		Controleur.chargementTermine();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentre = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        buttonAjouter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemQuitter = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        menuAide = new javax.swing.JMenu();
        itemAPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALMA Speech!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelCentre.setLayout(new java.awt.BorderLayout());

        toolBar.setRollover(true);

        buttonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        buttonAjouter.setText("Ajouter un cours");
        buttonAjouter.setEnabled(false);
        buttonAjouter.setFocusable(false);
        buttonAjouter.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        toolBar.add(buttonAjouter);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/text-speak.png"))); // NOI18N
        jButton1.setText("Commencer la capture!");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        toolBar.add(jButton1);

        panelCentre.add(toolBar, java.awt.BorderLayout.NORTH);

        getContentPane().add(panelCentre);

        menuFichier.setText("Fichier");

        itemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        itemQuitter.setText("Quitter");
        itemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuitterActionPerformed(evt);
            }
        });
        menuFichier.add(itemQuitter);

        menuBar.add(menuFichier);

        menuEdition.setText("Edition");
        menuBar.add(menuEdition);

        menuAide.setText("Aide");

        itemAPropos.setText("A propos...");
        itemAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAProposActionPerformed(evt);
            }
        });
        menuAide.add(itemAPropos);

        menuBar.add(menuAide);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void itemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuitterActionPerformed
		System.exit(0);
	}//GEN-LAST:event_itemQuitterActionPerformed

	private void itemAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAProposActionPerformed
		String mess = "<html><body>Speech root!<br><br>" +
				"Programme de reconnaissance vocale destiné aux personnes malentendente,<br>" +
				"basé sur le moteur de reconnaissance vocal speech root d'IBM.<br><br>";
        mess += "Programmé par :<br>" +
                "    -<a href=\"http://www.google.fr\">Braud Jérémy</a><br>" +
				"    -<a href=\"http://www.google.fr\">Hervouet Gaetan</a><br>" +
                "    -<a href=\"http://www.google.fr\">Krommenhoek Cédric</a><br>" +
				"    -<a href=\"http://www.google.fr\">Levin Damien</a>" +
				"</body></html>";
        JOptionPane.showMessageDialog(null, mess, "A propos", JOptionPane.INFORMATION_MESSAGE);
	}//GEN-LAST:event_itemAProposActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args) {
		new FenetrePrincipale().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JMenuItem itemAPropos;
    private javax.swing.JMenuItem itemQuitter;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu menuAide;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

	/**
	 * Initialisation de la fenetre.
	 */
	private void initialisation() {
		setLocationRelativeTo(null);

		PanelInfo panelInfo = new PanelInfo();
		getContentPane().add(panelInfo);

		PanelCentral panelCentral = new PanelCentral();
		this.panelCentre.add(panelCentral, java.awt.BorderLayout.CENTER);

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
			System.setProperty("apple.laf.useScreenMenuBar", "true");
			System.setProperty("com.apple.mrj.application.apple.menu.about.name", "ALMA Speech!");
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
	}

}
