/*
 * PanelInfo.java
 *
 * Created on 8 mars 2010, 10:00:11
 */

package fr.alma.asr.ihm;

/**
 * Classe gérant le panel d'information.
 * @author Braud Jeremy
 */
public class PanelInfo extends javax.swing.JPanel {

    /** Creates new form PanelInfo. */
    public PanelInfo() {
        initComponents();
		Controleur.setPanelInfo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInfo = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(labelInfo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelInfo)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables

	/**
	 * Modification de l'info.
	 * @param info l'info à afficher
	 */
	public void setInfo(String info) {
		this.labelInfo.setText(info);
	}

}
