/*
 * PanelCentral.java
 *
 * Created on 11 févr. 2010, 10:56:52
 */

package fr.alma.asr.ihm;

import fr.alma.asr.gui.tree.PanelArbreCours;
import fr.alma.asr.gui.tree.PanelArbrePlan;

import javax.swing.ImageIcon;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 * Le panel central de l'application.
 * @author Braud Jeremy
 */
public class PanelCentral extends javax.swing.JPanel {

    /**
	 * Creates new form PanelCentral.
	 */
    public PanelCentral() {
		initialisation();
        initComponents();
		postInit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        ongletsArbres = new javax.swing.JTabbedPane();
        ongletsEdition = new javax.swing.JTabbedPane();

        splitPane.setDividerLocation(120);
        splitPane.setLeftComponent(ongletsArbres);
        splitPane.setRightComponent(ongletsEdition);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ongletsArbres;
    private javax.swing.JTabbedPane ongletsEdition;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private DefaultMutableTreeNode racineCours;
    private DefaultMutableTreeNode racinePlan;
	private Controleur controleur;
	private PanelHome homePanel;

	private void initialisation() {
		this.controleur = Controleur.getInstance();
		this.racineCours = new DefaultMutableTreeNode("Cours");
		controleur.construireArbreCours(this.racineCours);
		this.racinePlan = new DefaultMutableTreeNode("Plan");
		controleur.construireArbrePlan(this.racinePlan);

		this.homePanel = new PanelHome();
	}

	private void postInit() {
		ongletsArbres.add("Cours", new PanelArbreCours());
		ongletsArbres.add("Plan", new PanelArbrePlan());

        ongletsEdition.addTab("Home", new ImageIcon("img/home24.png"), this.homePanel);
	}

}
