/*
 * PanelHome.java
 *
 * Created on 6 mars 2010, 11:16:52
 */

package fr.alma.asr.gui;

import fr.alma.asr.entities.Lesson;
import java.util.List;
import java.util.logging.Level;

/**
 * Panel d'acceuil.
 * @author Braud Jeremy
 */
public class HomePanel extends javax.swing.JPanel {

    /** Creates new form PanelHome. */
    public HomePanel() {
		initialisation();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelClasser = new javax.swing.JLabel();
        comboDate = new javax.swing.JComboBox();
        jScrollPane = new javax.swing.JScrollPane();
        panelCours = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        labelClasser.setText("Classer les cours par ordre de :");

        comboDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "création", "modification" }));
        comboDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDateItemStateChanged(evt);
            }
        });

        panelCours.setLayout(null);

        jLabel1.setText("jLabel1");
        panelCours.add(jLabel1);
        jLabel1.setBounds(0, 0, 34, 14);

        jLabel2.setText("jLabel2");
        panelCours.add(jLabel2);
        jLabel2.setBounds(20, 10, 34, 14);

        jLabel3.setText("jLabel3");
        panelCours.add(jLabel3);
        jLabel3.setBounds(20, 20, 34, 14);

        jLabel4.setText("jLabel4");
        panelCours.add(jLabel4);
        jLabel4.setBounds(20, 30, 34, 14);

        jLabel5.setText("jLabel5");
        panelCours.add(jLabel5);
        jLabel5.setBounds(0, 50, 34, 14);

        jLabel6.setText("jLabel6");
        panelCours.add(jLabel6);
        jLabel6.setBounds(20, 60, 34, 14);

        jScrollPane.setViewportView(panelCours);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelClasser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClasser)
                    .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void comboDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDateItemStateChanged
		this.classerParCreation = comboDate.getSelectedIndex() == 0;
		updateListeFichiers();
	}//GEN-LAST:event_comboDateItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelClasser;
    private javax.swing.JPanel panelCours;
    // End of variables declaration//GEN-END:variables

	private Controleur controleur;
	private Boolean classerParCreation;

	private void initialisation() {
		this.controleur = Controleur.getInstance();
		this.classerParCreation = Boolean.FALSE;
		updateListeFichiers();
	}

	private void updateListeFichiers() {
		List<Lesson> listeFichier = controleur.getListeFichiers(classerParCreation);
		for (Lesson fichier : listeFichier) {
			Controleur.printLog(Level.INFO, fichier.toString());
		}
	}

}
